version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  base-directory: ./build
  files:
    - '**/*'